language: bash
sudo: false

addons:
  apt:
    packages:
    - ruby

env:
  # - UNITY_VERSION=latest
  # - UNITY_VERSION=latest_stable
  # - UNITY_VERSION=latest_beta
  # - UNITY_VERSION=latest_patch
  - UNITY_VERSION=2019.2.11f1

before_install: ./ci/before_install.sh
install: ./ci/install.sh

cache:
  directories:
    - ~/Downloads/Unity_Packages/
