os: 
  - windows
  - osx
  - linux

language: bash
sudo: true

addons:
  apt:
    packages:
    - ruby

env:
  # - UNITY_VERSION=latest
  # - UNITY_VERSION=latest_stable
  # - UNITY_VERSION=latest_beta
  # - UNITY_VERSION=latest_patch
  - UNITY_VERSION=2019.1.0f2
  # - UNITY_VERSION=2019.2.11f1

before_install: chmod +x ./ci/*.sh && ./ci/before_install.sh
install: ./ci/install.sh

cache:
  directories:
    - ~/Downloads/Unity_Packages/
